ServerEvents.recipes(event => {
    event.replaceInput(
        { input: 'farmersdelight:rope' },
        'farmersdelight:rope',
        'supplementaries:rope'
    ),
    event.replaceOutput(
        { output: 'farmersdelight:rope' },
        'farmersdelight:rope',
        'supplementaries:rope'
    ),
    // Consolidate all doughs to Create dough
    event.replaceInput(
        { input: 'farmersdelight:wheat_dough' },
        'farmersdelight:wheat_dough',
        'create:dough'
    ),
    event.replaceOutput(
        { output: 'farmersdelight:wheat_dough' },
        'farmersdelight:wheat_dough',
        'create:dough'
    ),
    //REMOVE ARROWS (forcing player to use fletching table)
    event.remove({ output: 'quark:torch_arrow', type: 'minecraft:crafting_shapeless' }),
    event.remove({ output: 'alexsmobs:shark_tooth_arrow', type: 'minecraft:crafting_shaped' }),
    event.remove({ output: 'iceandfire:dragonbone_arrow', type: 'minecraft:crafting_shapeless' }),
    event.remove({ output: 'iceandfire:stymphalian_arrow', type: 'minecraft:crafting_shaped' }),
    event.remove({ output: 'iceandfire:amphithere_arrow', type: 'minecraft:crafting_shaped' }),
    event.remove({ output: 'iceandfire:sea_serpent_arrow', type: 'minecraft:crafting_shaped' }),
    event.remove({ output: 'iceandfire:hydra_arrow', type: 'minecraft:crafting_shaped' }),
    event.remove({ output: 'alexscaves:seeking_arrow', type: 'minecraft:crafting_shaped' }),
    event.remove({ output: 'alexscaves:burrowing_arrow', type: 'minecraft:crafting_shaped'}),
    event.remove({ output: 'minecraft:spectral_arrow', type: 'minecraft:crafting_shaped'}),
    event.remove({ output: 'netherexp:phasmo_arrow', type: 'minecraft:crafting_shaped'}),
    event.remove({ output: 'forbidden_arcanus:draco_arcanus_arrow', type: 'minecraft:crafting_shaped'}),
    //Remove Backpack Recipes (Reworked)
    event.remove({ id: 'sophisticatedbackpacks:diamond_backpack' }),
    event.remove({ id: 'sophisticatedbackpacks:gold_backpack' }),
    event.remove({ id: 'sophisticatedbackpacks:iron_backpack' }),
    event.remove({ id: 'sophisticatedbackpacks:iron_backpack_from_copper' }),
    event.remove({ id: 'sophisticatedbackpacks:copper_backpack' }),
    event.remove({ id: 'sophisticatedbackpacks:feeding_upgrade' }),
    event.remove({ id: 'sophisticatedbackpacks:advanced_feeding_upgrade' }),
    //Removals Misc (Most Reworked)
    event.remove({ output: 'netherexp:soul_jack_o_lantern'}),
    event.remove({ output: 'autumnity:pancake'}),
    event.remove({ output: 'supplementaries:pancake'}),
    event.remove({ output: 'alexsmobs:sopa_de_macaco' }),
    event.remove({ output: 'create:crushed_raw_uranium' }),
    event.remove({ id: 'apotheosis:enchanted_golden_apple' }),
    event.remove({ output: 'bountiful:bountyboard' }),
    event.remove({ output: 'create_enchantment_industry:disenchanter' }),
    event.remove({ output: 'upgrade_aquatic:beachgrass_thatch' }),    
    event.remove({ id: 'biomemakeover:phantom_membrane' }),  
    event.remove({ output: 'biomemakeover:poltergeist' }),  
    event.remove({ output: 'betterarcheology:bomb' }),   
    event.remove({ output: 'alexscaves:primitive_club' }),  
    event.remove({ output: 'alexscaves:tremorzilla_egg' }),  
    event.remove({ output: 'farmersdelight:cooking_pot' }), 
    event.remove({ output: 'quark:rusty_iron_plate' }), 
    event.remove({ output: 'create:iron_sheet'}),
    event.remove({ output: 'spelunkery:rope_ladder' }), 
    event.remove({ output: 'spelunkery:parachute' }), 
    event.remove({ output: 'biomemakeover:crude_cladding'}),
    event.remove({ output: 'oreganized:electrum_upgrade_smithing_template' }),
    event.remove({ id: 'minecraft:map'}),
    event.remove({ mod: 'inventorio'}),
    event.remove({ output: 'quark:iron_plate'}),
    event.remove({ output: 'biomemakeover:crab_chowder'}),
    event.remove({ output: 'biomemakeover:reed_thatch'}),
    event.remove({ output: 'ftbfiltersystem:smart_filter'}),
    event.remove({ output: 'netherexp:ecto_soul_sand'}),
    event.remove({ output: 'netherexp:nether_pizza'}),
    event.remove({ output: 'minecraft:soul_torch'}),
    event.remove({ output: 'minecraft:soul_campfire'}),
    event.remove({ output: 'betternether:basalt_slab'}),
    event.remove({ output: 'galosphere:salted_jerky'}),
    event.remove({ output: 'iceandfire:graveyard_soil' }),
    event.remove({ output: 'mynethersdelight:boiled_egg' }),
    event.remove({ output: 'quarkdelight:cloud_latte' }),
    event.remove({ output: 'create:sturdy_sheet' }),
    event.remove({ output: 'create:rope_pulley' }),
    event.remove({ output: 'galosphere:saltbound_tablet'}),
    event.remove({ output: 'spelunkery:rock_salt', type: 'create:crushing'}),
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'netherexp:polished_basalt_bricks', input: 'minecraft:polished_basalt'}),
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'betternether:bone_wall'}),
    event.remove({ output: 'netherexp:netherite_plating', type: 'minecraft:crafting_shaped'}),
    event.remove({ output: 'netherexp:necromium_plating', type: 'minecraft:crafting_shaped'}),
    event.remove({ output: 'netherexp:wither_bone_block', type: 'minecraft:crafting_shaped'}),
    event.remove({ output: 'minecraft:pumpkin_pie', input: 'born_in_chaos_v1:cultivated_pumpkin'}),
    event.remove({ output: 'galosphere:silver_upgrade_smithing_template' }),
    event.remove({ output: 'legendary_monsters:polished_diorite_pillar' }), 
    event.remove({ output: 'alexsmobs:transmutation_table', input: 'minecraft:nether_star' })
}
)